apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poly-shop-product-service
  name: poly-shop-product-service
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: poly-shop-product-service
status:
  loadBalancer: {}
