apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger-tracing
  name: jaeger-tracing
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-tracing
  strategy: {}
  template:
    metadata:
      labels:
        app: jaeger-tracing
    spec:
      containers:
      - image: jaegertracing/all-in-one:1.50
        name: jaegertracing
        resources: {}
        envFrom:
        - configMapRef:
           name: jaeger-cm
        ports:
        - containerPort: 16686
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 14268
        - containerPort: 9411
status: {}
