apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-tracing
  name: jaeger-tracing-svc
  namespace: observability
spec:
  ports:
  - name: ui
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: grpc-receiver-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-receiver-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: http-collector
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: zipkin-compatible-endpoint
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger-tracing
status:
  loadBalancer: {}
