apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger-tracing-svc.observability.svc.cluster.local:4317"
  REDIS_ADDR: "polyapp-redis.demo.svc.cluster.local:6379"
  ENVIRONMENT: "production"
kind: ConfigMap
metadata:
  name: cart-ms-cm
  namespace: demo
