apiVersion: v1
kind: Service
metadata:
  labels:
    app: poly-shop-checkout-ms
  name: poly-shop-checkout-ms-svc
  namespace: demo
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: poly-shop-checkout-ms
status:
  loadBalancer: {}
